### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by IamFalseBielfs** [h4ck3r0/kali-theme#5]
i cant use su command as any user anymore how do i uninstall and revert my terminal to get rid of this heinious application?

**Comment by h4ck3r0** [comment]
What ? I didn't got that issue and you will get an option to uninstall in same tool

**Comment by IamFalseBielfs** [comment]
It worked great but removed the access to su for all users except root and
a few other obsolete issues I ran into, with the uninstall please make it
also revert the shell to default as part as the prompt and ect… goes I
didn’t mean to be so derogative with my statement I was just extremely
tired so I’m sorry

**Comment by h4ck3r0** [comment]
I understand, you can check an option to uninstall theme or
